# Contributors {#contrib}

Jenny Bryan ([twitter](https://twitter.com/jennybryan), [GitHub](https://github.com/jennybc)) is a Software Engineer at [RStudio](https://www.rstudio.com), working on the team lead by [Hadley Wickham](http://hadley.nz). This team brings you the popular set of packages known as the [Tidyverse](https://www.tidyverse.org), as well as a set of [low-level infrastructure packages](https://github.com/r-lib/). She is on leave from being an Associate Professor of [Statistics at the University of British Columbia](https://www.stat.ubc.ca). Jenny has an undergraduate degree in Economics and German Literature from Yale University and earned her PhD in Biostatistics at UC Berkeley.

Jenny has been using and teaching R (or S!) for 20 years, most recently in [STAT 545](http://stat545.com) and [Software Carpentry](http://software-carpentry.org). Other aspects of her R life include ordinary membership in the [R Foundation](https://www.r-project.org/foundation/members.html), work with [rOpenSci](https://ropensci.org/about/#leadership), development/maintenance of [R packages](https://www.r-pkg.org/search.html?q=Jennifer+bryan) (such as [readxl](http://readxl.tidyverse.org)), and leading the curriculum development for [UBC's Master of Data Science](http://mds.science.ubc.ca).

The development and delivery of this material has benefited greatly from contributions by:

  * Dean Attali ([blog](http://deanattali.com), [GitHub](https://github.com/daattali/), [twitter](https://twitter.com/daattali)) who earned his M.Sc. Bioinformatics at UBC. He's the developer of the [shinyjs](https://github.com/daattali/shinyjs) package and [much more](http://deanattali.com/projects/).
  * Bernhard Konrad ([GitHub](https://github.com/BernhardKonrad), [twitter](https://twitter.com/bernhardkonrad)) earned his Ph.D. in Applied Math at UBC, completed an [Insight Data Science Fellowship](http://www.insightdatascience.com), and is a software engineer at Google.
  * Shaun Jackman ([GitHub](https://github.com/sjackman), [twitter](https://twitter.com/sjackman), [sjackman.ca](http://sjackman.ca)) is a Ph.D. student in bioinformatics at UBC, the lead developer of [Linuxbrew](http://linuxbrew.sh) and a developer of [Homebrew-Science](https://github.com/Homebrew/homebrew-science) and the genome sequence assembly software [ABySS](https://github.com/bcgsc/abyss)
  * Jim Hester ([GitHub](https://github.com/jimhester), [twitter](https://twitter.com/jimhester_), [jimhester.com](https://www.jimhester.com)) is a Software Engineer at [RStudio](https://www.rstudio.com).
  * The [STAT 545 TA group](http://stat545.com/people.html)
  * A growing number of [GitHub contributors](https://github.com/jennybc/happy-git-with-r/graphs/contributors)
