# Workshops

These materials can be used for independent study, but I also use them to support

  * in-person workshops (see below)
  * [STAT 545](http://stat545.com) at UBC
  * [UBC Master of Data Science](http://masterdatascience.science.ubc.ca)

## Pre-workshop set-up

Optional reading on the big picture motivation: [Why Git? Why GitHub?](#big-picture)

**It is vital that you attempt to set up your system in advance. You cannot show up at with no preparation and keep up!**

These are battle-tested instructions, so most will succeed. We believe in you! If you have trouble, you can open an issue [here](https://github.com/jennybc/happy-git-with-r/issues) and we *might* be able to help in the days leading up to your workshop (no promises).

Try this. Give it about 1 - 2 hours. If you hit a wall, we will help:

  * [Register a free GitHub account](#github-acct).
  * [Install or update R and RStudio](#install-r-rstudio).
  * [Install Git](#install-git).
  * [Introduce yourself to Git](#hello-git).
  * [Prove local Git can talk to GitHub](#push-pull-github).
  * [Cache your username and password](#credential-caching) or [set up SSH keys](#ssh-keys) so you don't need to authenticate yourself to GitHub interactively *ad nauseum*.
  * [Prove RStudio can find local Git](#rstudio-git-github) and, therefore, can talk to GitHub.
    - FYI: this is where our hands-on activities usually start. We walk through a similar activity together, with narrative, and build from there.

Troubleshooting:

  * Sometimes RStudio [needs a little help finding Git](#rstudio-see-git).
  * General troubleshooting: [RStudio, Git, GitHub Hell](#troubleshooting).

## useR! 2016 Stanford

Monday, June 27, 2016  
8:15am - 9:00 TAs available to help complete system set up  
9:00am - 12:00pm Workshop, with coffee break 10:15am - 10:30am  
Lyons & Lodato 326 Galvez Street Stanford, CA 94305-6105 [Google Maps](https://goo.gl/maps/wkvKkBkbs1J2)  
Sessions in the useR! schedule website: [part 1](http://schedule.user2016.org/event/7Bad/using-git-and-github-with-r-rstudio-and-r-markdown-part-1), [part 2](http://schedule.user2016.org/event/7Bav/using-git-and-github-with-r-rstudio-and-r-markdown-part-2)  
[Full description](http://user2016.org/tutorials/01.html) on the main useR! website  

<!--    
### What we can do together

  * Verify and complete the most difficult part: installation and configuration!
  * Create a Git repository and connect the local repo to a GitHub remote, for new and existing projects.
  * Run R code, via R Markdown or a script, and share a presentable report via GitHub.
  * The intersection of GitHub and the R world:
    - R packages developed on GitHub and how to make use of [Issues](https://guides.github.com/features/issues/)
    - [METACRAN](http://www.r-pkg.org) [read-only mirror](https://github.com/cran) of all of CRAN + R-specific searching tips.
  * Propose a change to someone else's project, i.e. "make a [pull request](https://help.github.com/articles/using-pull-requests/)".
  * Discuss daily workflow:
    - How often should I commit? Which files should I commit?
    - Data files and the dilemmas they present.
    - Most common Git predicaments. How to avoid and recover.
    - How do groups of 1, 5, or 10 people structure their work with Git(Hub)?
-->

## CSAMA 2016: Statistical Data Analysis for Genome Biology

<http://www.huber.embl.de/csama2016/>  
July 10 - 15, 2016, Bressanone-Brixen, Italy  
Monday July 11, Lab 2, 15:30 - 17:00 Use of Git and GitHub with R, RStudio, and R Markdown  
Thursday July 14, Lab 4, 14:00 - 15:30 Reproducible research and R authoring with markdown and knitr  
