# (PART) Installation {-} 

# Installation pain

Getting all the necessary software installed, configured, and playing nicely together is honestly half the battle here. Brace yourself for some pain. The upside is that you can give yourself a pat on the back once you get through this. And you WILL get through this.

You will find far more resources for how to *use Git* than for installation and configuration. Why? The experts ...

  * Have been doing this for years. It's simply not hard for them anymore.
  * Probably use some flavor of Unix. They may secretly (or not so secretly) take pride in neither using nor knowing Windows.
  * Get more satisfaction and reward for thinking and writing about Git concepts and workflows than Git installation.

In their defense, it's hard to write installation instructions. Failures can be specific to an individual OS or even individual computer. If you have some new problem and, especially, the corresponding solution, [we'd love to hear from you!](https://github.com/jennybc/happy-git-with-r/issues)

## Success and operating systems

<style type="text/css">
#success-and-operating-systems table {
  width: auto;
}
</style>

Our installation instructions have been forged in the fires of [STAT 545](http://stat545.com), [STAT 540](https://stat540-ubc.github.io), and assorted workshops, over several years. We regularly hear from [grateful souls on the internet](https://twitter.com/millsGT49/status/647059167509921793) who also have success.

Here's some recent data on the subset of STAT 545 students for which we recorded the operating system: half Mac, just under half Windows (various flavours), and a dash of Linux. 

|            |     2014 |     2015 |
|-----------:|---------:|---------:|
|        Mac | 16 (41%) | 38 (52%) |
|  Windows 7 |  9 (23%) | 13 (18%) |
|  Windows 8 | 12 (31%) |  9 (12%) |
| Windows 10 |   0 (0%) |  8 (11%) |
|      Linux |   2 (5%) |   5 (7%) |

