# Installation: One thing at a time

We need to set up several individual components and test individually, before we attempt to integrate:

  * Register a GitHub account, section \@ref(register-github).
  * Install or upgrade R and RStudio, section \@ref(register-github).
  * Install Git, section \@ref(register-github).
  * Install a Git client, section \@ref(register-github).

## Register a GitHub account {#register-github}

Register an account with GitHub. It's free!

  * <https://github.com>
  
You will be able upgrade to a paid level of service, apply discounts, join organizations, etc. in the future, so don't worry about any of that now. **Except your username. You should actually worry about that.**

A few tips, which sadly tend to contradict each other:

  * Incorporate your actual name! People like to know who they're dealing with. Also makes your username easier for people to guess or remember.
  * Reuse your username from other contexts, e.g., Twitter or Slack. But, of course, someone with no GitHub activity will probably be squatting on that.
  * Pick a username you will be comfortable revealing to your future boss.
  * Shorter is better than longer.
  * Be as unique as possible in as few characters as possible. In some settings GitHub auto-completes or suggests usernames.
  * Make it timeless. Don't highlight your current university, employer, or place of residence (like I have, sigh).
  * Avoid words laden with special meaning in computer programming. In my first inept efforts to script around the GitHub API, I assigned lots of issues to [the guy with username `NA`](https://github.com/na) because my vector of GitHub usernames contained missing values. A variant of [Little Bobby Tables](https://xkcd.com/327/).

You can change your username later, but better to get this right the first time.

  * <https://help.github.com/articles/changing-your-github-username/>
  * <https://help.github.com/articles/what-happens-when-i-change-my-username/>

GitHub offers free access to paid levels of service -- unlimited private repositories for $0!!! -- for some classes of people. Go ahead and register your free acount NOW and then pursue any special offer that applies to you:

  * Students, faculty, and educational/research staff should go here: [GitHub Education](https://education.github.com).
    - Free unlimited private repos for individuals.
    - Organizations with unlimited private repos for use in class, research group, lab, etc.
  * Official nonprofit organizations and charities should go here: <https://github.com/nonprofit>

## Install or upgrade R and RStudio.

**Get current, people.** You don't want to adopt new things on day one. But at some point, running old versions of software adds unnecessary difficulty.

In live workshops, there is a limit to how much we can help with ancient versions of R or RStudio. Also, frankly, there is a limit to our motivation. By definition, these problems are going away and we'd rather focus on edge cases with current versions, which affect lots of people.

For now, just go here:

<http://stat545.com/block000_r-rstudio-install.html>

*not sure whether to move or duplicate that content*

## Install Git

Bring this over:

<http://stat545.com/git01_git-install.html>

And this too:

<http://stat545.com/git04_introduce-self-to-git.html>

## Install a Git client

Optional but recommended.

Bring this over:

<http://stat545.com/git02_git-clients.html>
