# (PART) Installation {-} 

# Half the battle {#install-intro .unnumbered}

Getting all the necessary software installed, configured, and playing nicely together is honestly half the battle when first adopting Git. Brace yourself for some pain. The upside is that you can give yourself a pat on the back once you get through this. And you WILL get through this.

You will find far more resources for how to *use Git* than for installation and configuration. Why? The experts ...

  * Have been doing this for years. It's simply not hard for them anymore.
  * Probably use some flavor of Unix. They may secretly (or not so secretly) take pride in neither using nor knowing Windows.
  * Get more satisfaction and reward for thinking and writing about Git concepts and workflows than Git installation.

In their defense, it's hard to write installation instructions. Failures can be specific to an individual OS or even individual computer. If you have some new problem and, especially, the corresponding solution, [we'd love to hear from you!](https://github.com/jennybc/happy-git-with-r/issues)

## Success and operating systems {-}

<style type="text/css">
#success-and-operating-systems table {
  width: auto;
}
</style>

Our installation instructions have been forged in the fires of [STAT 545](http://stat545.com), [STAT 540](https://stat540-ubc.github.io), and assorted workshops, over several years. We regularly hear from [grateful souls](https://twitter.com/ibddoctor/status/777610645617475584) [on the internet](https://twitter.com/millsGT49/status/647059167509921793) who also have success.

Here's data on the operating systems we encounter in STAT 545 and other workshops: overall the bulk are split sort of evenly between Mac and Windows (various flavours), with a dash of Linux. Except in a BioConductor context (CSAMA), which is dominated by Mac or Linux.

|             |     2014 |     2015 |     2016 | useR! 2016 | CSAMA 2016 | CSAMA 2017 | r::c 2018 | seattle 2018 |
|------------:|---------:|---------:|---------:|-----------:|-----------:|-----------:|----------:|-------------:|
|        Mac  | 16 (41%) | 38 (52%) | 37 (45%) |   28 (44%) |   25 (58%) |   23 (56%) |  51 (57%) |      16 (49%) |
| Windows 10* |   0 (0%) |  8 (11%) | 30 (36%) |   27 (43%) |    6 (14%) |    8 (20%) |  19 (21%) |      12 (36%) |
|  Windows 8  | 12 (31%) |  9 (12%) |  4  (5%) |            |            |    1 ( 2%) |   2  (2%) |               |
|  Windows 7  |  9 (23%) | 13 (18%) | 10 (12%) |            |            |    1 ( 2%) |  13 (14%) |       4 (12%) |
|      Linux  |   2 (5%) |   5 (7%) |  2  (2%) |    8 (13%) |   12 (28%) |    9 (20%) |   5  (6%) |       1  (3%) |

\* Windows 10 is the Windows catchall, when I don't have more specific info.
